name: Tag Production Post-Merge
on:
  pull_request:
    branches:
    - master
    types:
    - closed


jobs:

  tag_prod:
    runs-on: ubuntu-latest
    steps:

    - name: Set App Version and Name Vars
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        echo ::set-env name=TEST_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-dev")
        echo ::set-env name=MY_PROD_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-prod")


## Set target Docker image based on new pull request label

    - name: Tag Prod
      if: github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker pull docker.pkg.github.com/$TEST_APP:$GITHUB_HEAD_REF
        docker tag docker.pkg.github.com/$TEST_APP:$GITHUB_HEAD_REF docker.pkg.github.com/$MY_PROD_APP:$GITHUB_REF
        docker tag docker.pkg.github.com/$TEST_APP:$GITHUB_HEAD_REF docker.pkg.github.com/$MY_PROD_APP:latest
        docker push docker.pkg.github.com/$MY_PROD_APP:$GITHUB_REF
        docker push docker.pkg.github.com/$MY_PROD_APP:latest